/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "mars-sim"
include(":Modules:mars-sim-console")
include(":Modules:mars-sim-core")
include(":Modules:mars-sim-tools")
include(":Modules:mars-sim-headless")
include(":Modules:mars-sim-ui")
include(":Modules:mars-sim-dist")
include(":Modules:mars-sim-map-viewer")
