/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.mars-sim.java-conventions")
}

dependencies {
    api(project(":Modules:mars-sim-core"))
    api(libs.org.springframework.spring.core)
    api(libs.com.github.spullara.mustache.java.compiler)
    testImplementation(libs.org.jsoup.jsoup)
}

description = "mars-sim-tools"
