/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.mars-sim.java-conventions")
}

dependencies {
    api(project(":mars-sim-core"))
    api(libs.org.beryx.text.io)
    api(libs.org.apache.sshd.sshd.core)
    testImplementation(libs.org.hamcrest.hamcrest.core)
}

description = "mars-sim-console"
