/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.mars-sim.java-conventions")
}

dependencies {
    api(project(":Modules:mars-sim-console"))
    api(libs.org.apache.commons.commons.lang3)
    api(libs.commons.cli.commons.cli)
    api(libs.org.slf4j.slf4j.api)
}

description = "mars-sim-headless"
