/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.mars-sim.java-conventions")
}

dependencies {
    api(project(":mars-sim-core"))
    api(project(":mars-sim-tools"))
    api(project(":mars-sim-headless"))
    api(libs.org.jfree.jfreechart)
    api(libs.org.bidib.jbidib.eu.hansolo.steelseries)
    api(libs.org.apache.xmlgraphics.batik.transcoder)
    api(libs.com.googlecode.soundlibs.jorbis)
    api(libs.com.formdev.flatlaf.swingx)
    api(libs.com.formdev.flatlaf.extras)
    api(libs.com.formdev.flatlaf)
    api(libs.com.formdev.flatlaf.jide.oss)
    api(libs.com.formdev.jide.oss)
}

description = "mars-sim-ui"
