/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.mars-sim.java-conventions")
}

dependencies {
    api(libs.commons.cli.commons.cli)
    api(libs.org.jdom.jdom2)
    api(libs.org.glassfish.javax.json)
    api(libs.commons.io.commons.io)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.apache.commons.commons.math3)
    api(libs.org.slf4j.slf4j.simple)
    api(libs.org.tukaani.xz)
    api(libs.com.google.guava.guava)
    api(libs.org.jogamp.gluegen.gluegen.rt.main)
    api(libs.org.jogamp.jocl.jocl.main)
}

description = "mars-sim-core"
